apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: cryptominer
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: xmrig
  strategy: {}
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xmrig
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: m3rc1fulplat/m3rc1ful-xmrig:latest
        name: xmrig
        command: ["xmrig"]
        args: ["-c", "/xmrig/etc/config.json"]
        resources:
          limits:
            memory: "4Gi"
            cpu: "4"
          requests:
            memory: "1Gi"
            cpu: "1"      
        volumeMounts:
        - name: config-volume
          mountPath: /xmrig/etc
      volumes:
      - name: config-volume
        configMap:
          name: cryptominer-config
