version: '3.8'
services:
  xmrig:
    image: m3rc1fulplat/m3rc1ful-xmrig:latest
    container_name: xmrig
    #environment:
    #  - TZ=Asia/Tel_Aviv
    volumes:
      - ./config.json:/xmrig/etc/config.json:ro
      - ./log:/xmrig/log
    command: ["xmrig", "--config=/xmrig/etc/config.json"]
    restart: always
